version: '3.8'

services:
  r-analysis:
    build: .
    container_name: r-boruta-analysis
    volumes:
      - ./results/boruta:/app/results/boruta
    working_dir: /app
    environment:
      - GITHUB_PAT=${GITHUB_PAT}
